USE buscamecanica;


CREATE TABLE TBL_PESSOA (
    ID_PESSOA INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
	CPF CHAR(11) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE ,
    
    PRIMARY KEY (ID_PESSOA)
);

CREATE TABLE TBL_CLIENTE(
	ID_OFCINA INT AUTO_INCREMENT NOT NULL,
    FK_CPF_CLIENTE CHAR(11) NOT NULL,
    HABILITACAO_CLIENTE VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID_OFICINA),
	FOREIGN KEY(FK_CPF_CLIENTE) REFERENCES TBL_PESSOA(CPF)
    
    
    
);

CREATE TABLE TBL_OFICINA(
	ID_OFICINA INT AUTO_INCREMENT NOT NULL,
	CNPJ CHAR(14) NOT NULL,
	IE VARCHAR(10) NOT NULL,
	FK_CPF_PROPRIETARIO  CHAR(11) NOT NULL,
	SITE VARCHAR(255),
	EMAIL_OFICINA VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_OFICINA),
    FOREIGN KEY(FK_CPF_PROPRIETARIO) REFERENCES TBL_PESSOA(CPF)

  

 
);

CREATE TABLE TBL_VEICULOS(
	ID_VEICULO INT NOT NULL AUTO_INCREMENT,
    PLACA VARCHAR(10) NOT NULL,
    FK_CPF_PROPRIETARIO_CARRO CHAR(11) NOT NULL,
    ANO_FABRICACAO DATE NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    COR VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_VEICULO),
    FOREIGN KEY(FK_CPF_PROPRIETARIO_CARRO) REFERENCES TBL_PESSOA(CPF)




);

CREATE TABLE TBL_SERVICOS(
	ID_SERVICOS INT AUTO_INCREMENT NOT NULL,
    NOME_SERVICO VARCHAR(50) NOT NULL,
    DESCRICAO_SERV VARCHAR(255),
    MAO_DE_OBRA REAL(12,2) NOT NULL,
	PRIMARY KEY (ID_SERVICOS)
    
);

CREATE TABLE TBL_PECAS(
	ID_PECA INT AUTO_INCREMENT NOT NULL,
	NOME_PECA VARCHAR(50) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL, 
	PRIMARY KEY (ID_PECA)


);
CREATE TABLE TBL_ENDERECOS(
	id_endereco INT AUTO_INCREMENT NOT NULL,
	rua VARCHAR(50) NOT NULL,
	bairro VARCHAR(50) NOT NULL,
	cidade VARCHAR(50) NOT NULL,
	estado CHAR(2) NOT NULL,
	pais VARCHAR(50) NOT NULL,
	complemento VARCHAR(50) NOT NULL,
	cep VARCHAR(7) NOT NULL,
	numero VARCHAR(10) NOT NULL,
	PRIMARY KEY (id_endereco)


);
